config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "home#index"
  get 'articles/index', as: 'user_root'
  
  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: {:new => ''} #более красивый способ, чем приведенный выше

  resources :articles do
    resources :comments #, only: [:new, :create, :destroy]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username #добавляем имя пользователя в массив данных, получаемых при регистрации пользователя
    devise_parameter_sanitizer.for(:sign_in) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @articles = Article.all
  end

  def new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.valid?
      @article.save
      redirect_to @article #автоматически перенаправляет на страницу /articles/id, где id - id-шник свежесозданной статьи. вьюха create в данном случае больше не нужна.
    else
      render action: 'new'
    end

  end

  def edit
    @article = Article.find(params[:id]) 
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article #автоматически перенаправляет на страницу /articles/id, где id - id-шник свежесозданной статьи. вьюха create в данном случае больше не нужна.
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end


  private #все методы ниже будут недоступны извне, только из методов этого контроллера

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  def show
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @article #автоматически перенаправляет на страницу /articles/id, где id - id-шник свежесозданной статьи. вьюха create в данном случае больше не нужна.
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @article.comments.destroy(params[:id])
    # @article.destroy
    redirect_to article_path(@article)
  end

  private #все методы ниже будут недоступны извне, только из методов этого контроллера

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end


  private #все методы ниже будут недоступны извне, только из методов этого контроллера

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h1>Записано</h1>
<!-- <a href="/articles">показать все статьи</a> -->
<%= link_to 'показать все статьи', articles_path %>

app/views/articles/edit.html.erb
<h1>Редактирование</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<p>
		<%= f.label 'Заголовок' %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label 'Текст статьи' %><br>
		<%= f.text_area :text %>
	</p>
	<p>
		<%= f.submit %>
	</p>


<% end %>

app/views/articles/index.html.erb
<h1>Все статьи</h1>

<%= link_to 'новая запись', new_article_path %>

<% @articles.each do |article| %>

<h3>
	<%= article.title %>
</h3>
<p>
	<%= article.text %>
</p>
<p>
	<%= link_to 'показать', article_path(article) %> |
	<%= link_to 'редактировать', edit_article_path(article) %> |
	<%= link_to 'удалить', article_path(article), method: :delete, data: { confirm: 'Вы уверены?' } %>
</p>

<hr>

<% end %>

app/views/articles/new.html.erb
<h1>New Atricles</h1>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>
	<p>
		<%= f.submit %>
	</p>


<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.text %></p>

<%= link_to 'вернуться', articles_path %>

<h2>Комментарии:</h2>

<% @article.comments.each do |comment| %>
	<p>
	<i><%= comment.author %> сказал:</i>
	<%= comment.body %>
	<%= link_to 'del', article_comment_path(@article, comment), method: :delete, data: { confirm: 'Вы уверены?' } %>
	<%= link_to 'edit', edit_article_comment_path(@article, comment) %>
	</p>
<% end %>

<p>
	<%= form_for([@article, @article.comments.build]) do |f| %>
		<p>
			<%= f.label 'Автор' %><br>
			<%= f.text_field :author %>
		</p>
		<p>
			<%= f.label 'Комментарий' %><br>
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.submit %>
		</p>
	<% end %>


</p>

app/views/comments/edit.html.erb
<p>
	<%= form_for :comment, url: article_comment_path(@article, @comment), method: :put do |f| %>
		<p>
			<%= f.label 'Автор' %><br>
			<%= f.text_field :author %>
		</p>
		<p>
			<%= f.label 'Комментарий' %><br>
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.submit 'Send' %>
		</p>
	<% end %>


</p>

app/views/contacts/create.html.erb
<p>Спасибо</p>

app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %> <!-- если переменная определена, что выводим сообщения об ошибке, если нет - то и не паримся -->
	<p>
		<ul>
		<% @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</p>
	<% end %>

	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :message %><br>
		<%= f.text_area :message %>
	</p>
	<p>
		<%= f.submit 'Send message' %>
	</p>


<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blojik</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <a href="/users/sign_in">Sign In</a> | <a href="/users/sign_out" data-method="delete">Sign Out</a> -->
<% if user_signed_in? %>
	Вы зашли, как <%= current_user.username %> | <%= link_to 'выйти', destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to 'войти', new_user_session_path %> или <%= link_to 'зарегистрироваться', new_user_registration_path %>
<%end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h2>О себе... потом</h2>

app/views/pages/terms.html.erb
<h2>Ваще не знаю, зачем эта страница</h2>